Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 10
  WriteTimeout: 10
MySQL:
  Host: 127.0.0.1:3306
  DBName: sau_ossa_db
  Username: root
  Password: shiluo
  Charset: utf8mb4
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  Host: 127.0.0.1
  DB: 0
  Password: 123456
JWT:
  Secret: shiluo
  Issuer: go_qrcode_login
  Expire: 7200